"""Second release: ten decision-focused studies, authored 3 October 2026."""
SOURCES={
 'stress_principles':{'title':'BCBS (2018), Stress testing principles','url':'https://www.bis.org/bcbs/publ/d450.htm','application':'Scenario design and governance motivation. The four assumed shocks are not a regulatory stress test or estimated crisis probabilities.'},
 'tsmom':{'title':'Moskowitz, Ooi & Pedersen (2012), Time Series Momentum','url':'https://www.aqr.com/Insights/Research/Journal-Article/Time-Series-Momentum','application':'Motivates lagged own-return signals. Our monthly long/cash ETF rule is not a replication of the paper’s futures strategy.'},
 'volmanaged':{'title':'Moreira & Muir (2016/2017), Volatility-Managed Portfolios','url':'https://www.nber.org/papers/w22208','application':'Motivates exposure sensitivity to realised volatility. Our capped volatility target differs from the paper’s inverse-variance factor portfolios.'},
 'hac':{'title':'Newey & West (1986/1987), A Simple, Positive Semi-Definite, Heteroskedasticity and Autocorrelation Consistent Covariance Matrix','url':'https://www.nber.org/papers/t0055','application':'OLS coefficient uncertainty uses a Bartlett-weighted HAC estimator with five lags. Approximate intervals do not establish causal exposures.'},
 'drawdown':{'title':'Chekhlov, Uryasev & Zabarankin (2005), Drawdown Measure in Portfolio Optimization','url':'https://researchconnect.stonybrook.edu/en/publications/drawdown-measure-in-portfolio-optimization/','application':'Motivates path-dependent loss analysis. The project measures episodes and block-resampling sensitivity; it does not solve the paper’s optimisation problem.'},
 'backtesting':{'title':'Basel Framework MAR32, Backtesting requirements','url':'https://www.bis.org/committees/bcbs/basel-framework/standard/mar/32/inforce/2023-01-01/published/2020-03-27','application':'Motivates comparison of lagged risk forecasts with subsequent losses. Coverage diagnostics here are educational, not a regulatory backtest or model certification.'},
 'blackscholes':{'title':'Black & Scholes (1973), The Pricing of Options and Corporate Liabilities','url':'https://doi.org/10.1086/260062','application':'European call/put pricing at assumed constant volatility, with put–call parity tested. No market-implied volatility or tradable quote is inferred.'},
 'cboehedges':{'title':'Cboe (2021), Hedging Downside Exposure with PPUT, CLL and CLLZ Indices','url':'https://www.cboe.com/insights/posts/benchmark-indices-series-hedging-downside-exposure-with-pput-cll-and-cllz-indices/','application':'Institutional context for protective puts and collars. Synthetic strikes and costs do not replicate a Cboe benchmark.'},
 'proper_scores':{'title':'Gneiting & Raftery (2007), Strictly Proper Scoring Rules, Prediction, and Estimation','url':'https://doi.org/10.1198/016214506000001437','application':'Motivates recording probabilities before outcomes and scoring with binary Brier loss. A theoretical demonstration is kept separate from personal evidence.'}
}

def project(id,title,category,module,question,method,decision,falsifier,next,interview,sources,routes,status):
    return dict(id=id,title=title,category=category,module=module,question=question,method=method,decision=decision,falsifier=falsifier,next=next,interview=interview,sources=sources,routes=routes,status=status,authored='2026-10-03')

PROJECTS=[
 project('stress','Cross-asset stress laboratory','Portfolio construction','stress.py',
 'What breaks when rates, equities, crypto and currencies move together?',
 'Apply four explicit, hypothetical joint shocks to the 25 September holdings. Revalue local returns and EUR conversion with their interaction. Approximate IEF and SHY with assumed duration and convexity; reconcile holding-level impacts to total NAV.',
 'Use the largest losses to identify common exposures and specify an acceptable loss budget before considering any hedge.',
 'Different FX behaviour, convexity, correlations or liquidity can reverse the scenario ranking. Shock sizes are assumptions, not estimated percentiles.',
 'Source dated ETF duration and curve data, add spread and liquidity shocks, and map fund economic currency exposures.',
 'Why can a positive USD move cushion losses for a EUR investor? Which cross term is lost by adding local and currency returns?',
 ['stress_principles','archive'],[['current','Current weights'],['fixed-income','Rates thesis']],'Hypothetical joint shocks'),
 project('currency','EUR currency hedge frontier','Performance & FX','currency.py',
 'How sensitive is portfolio risk to partial currency hedging and its cost?',
 'Compare zero, half, full and estimated minimum-variance hedging of opening USD-listed notional. Estimate the hedge coefficient using observations through 27 September 2024; evaluate later observations with three assumed annual carry drags. Current weights make this a retrospective exposure experiment.',
 'Separate currency protection from expected carry. Compare risk reduction with a cost hurdle before acquiring an actual forward.',
 'Quotation currency is not economic exposure. Daily reset assumptions, proxy basis and changing covariance may make a calculated hedge inappropriate.',
 'Archive executable EUR/USD forward points and fund look-through before documenting a prospective hedge policy.',
 'Derive Cov(portfolio, hedge-leg)/Var(hedge-leg). Why is hedging every USD-listed ETF potentially an overhedge?',
 ['basis','archive'],[['fx','FX research'],['project/attribution','Price / FX attribution']],'Historical proxy sensitivity'),
 project('factors','Factor exposure and model fragility','Portfolio construction','factors.py',
 'How much of the basket is explained by equity, duration and gold proxies?',
 'Regress the fixed current-weight EUR basket on VT, IEF minus SHY, and GLD. Compare pre-inception and recent 252-session windows. Show Newey–West uncertainty, residual volatility, correlation conditioning and first principal-component share.',
 'Identify broad drivers and exposure instability. Large R-squared can be mechanical because regressors are also portfolio holdings.',
 'Omitted factors, overlap, collinearity and shifting coefficients undermine interpretation. The intercept is not a risk-free-adjusted alpha estimate.',
 'Use non-overlapping, investable factors, explicit EUR cash returns and rolling out-of-sample attribution.',
 'Distinguish statistical fit, investable factor returns and causal explanation; explain why HAC errors do not cure misspecification.',
 ['hac','archive'],[['current','Portfolio'],['project/risk','Risk contributions']],'Descriptive regression'),
 project('trend','Trend rule with delayed execution','Systematic strategies','trend.py',
 'Does a transparent long/cash trend rule change the portfolio’s loss profile?',
 'Use each instrument’s lagged 252-session EUR return to retain its original weight or move that sleeve to cash. Review monthly and fill only at the next available common close. Compare the same initial allocation without the signal; report all 126/189/252-session and cost sensitivities.',
 'Evaluate drawdown, cash drag, turnover and implementation together. Do not select a parameter because it maximises this short sample’s return.',
 'Whipsaws, slow re-entry, stale common dates and hindsight in selecting the universe can erase apparent protection.',
 'Preregister one rule and cost assumption, then log forward signals without tuning on the new observations.',
 'Explain the distinction between a past-return signal, its later executable fill, and the published futures momentum literature.',
 ['tsmom','archive'],[['project/rebalancing','Baseline trading rules']],'Retrospective policy experiment'),
 project('volcontrol','Cash-funded volatility targeting','Systematic strategies','volcontrol.py',
 'What does reducing exposure after volatility rises cost and protect?',
 'Estimate 60-session realised EUR basket volatility using only available closes. Scale original risky targets by target-volatility/estimated-volatility, clipped to 25–100%; review monthly and fill later. Compare 8%, 10%, 12% targets and zero/base/double transaction costs.',
 'Treat exposure control as a risk policy with cash drag and turnover. A target is an estimator input, not a guaranteed realised volatility.',
 'Gaps can occur before risk is reduced; rapid recoveries can punish delayed re-entry. The policy cannot lever up when the portfolio is below target.',
 'Specify a prospective volatility band, review cadence and financing assumptions before comparing realised forward risk.',
 'Why is inverse volatility not inverse variance? Why does no leverage make a low-volatility regime asymmetric?',
 ['volmanaged','archive'],[['project/risk','Risk estimation'],['project/rebalancing','Rebalancing']],'Capped exposure experiment'),
 project('drawdowns','Drawdown and recovery anatomy','Risk validation','drawdowns.py',
 'How deep and how long were losses, and how path-dependent is that result?',
 'Extract peak–trough–recovery episodes from the reconstructed NAV, including unrecovered episodes. Separately resample the current-weight return proxy into 600 one-year paths at block lengths 1, 5 and 20; retain the full sensitivity rather than selecting a favourable block.',
 'Discuss both capital loss and time underwater. The drawdown tolerated by an investor may differ from a one-day VaR budget.',
 'Resampling cannot create unseen crises. Current weights and stationary historical blocks may be poor approximations to future regimes.',
 'Extend history across distinct crises and compare explicit liquidity stresses with prospective risk limits.',
 'Why is maximum drawdown not a one-day risk statistic? What information is lost when returns are randomly reordered?',
 ['drawdown','archive'],[['current','Portfolio path'],['project/stress','Stress scenarios']],'Path-risk diagnostic'),
 project('varchecks','VaR forecast coverage checks','Risk validation','varchecks.py',
 'Do simple daily loss forecasts produce the expected number of breaches?',
 'Create lagged 250-session historical and exponentially weighted Gaussian risk forecasts at 95% and 99%. Count later exceedances, show Wilson coverage intervals, Kupiec unconditional-coverage likelihood ratios and descriptive adjacent-breach counts.',
 'Check both frequency and clustering before relying on a risk number. A model that passes a small-sample coverage check can still miss crisis losses.',
 'The fixed current-weight proxy is hindsight-based. Gaussian tails, sparse 99% exceptions and asymptotic p-values limit inference; clustering is not formally tested here.',
 'Maintain a prospective ledger of forecasts and realised hypothetical P&L; add independent clustering and tail-severity tests.',
 'Why does unconditional coverage fail to detect clustered breaches? Explain the zero-exception edge case.',
 ['backtesting','archive'],[['project/risk','VaR / ES estimates']],'Educational backtest'),
 project('crypto-budget','Crypto allocation and correlation stress','Crypto research','crypto_budget.py',
 'How much risk can a small Bitcoin/Ether allocation consume?',
 'Hold the other current weights fixed and fund 0–5% crypto allocations from EUR cash in the existing BTC/ETH proportion. Show Euler variance shares and an explicitly positive-semidefinite correlation stress. Audit whether weekend price pairs are actually present.',
 'Set crypto exposure by its impact on total portfolio risk and liquidity, not only by its small capital weight.',
 'The common-market calendar omits weekend moves; past covariance excludes custody losses and may understate deleveraging.',
 'Acquire a complete daily crypto archive and document custody, venue and gap scenarios before increasing the paper allocation.',
 'Explain why capital weight and variance share differ and why an arbitrary shocked correlation matrix may be invalid.',
 ['crypto','archive'],[['asset/bitcoin','Bitcoin sleeve'],['project/stress','Joint stress']],'Cash-funded sizing sensitivity'),
 project('option-hedges','Protective puts and collar economics','Derivatives research','optionhedges.py',
 'What is the actual trade-off between downside protection, premium and foregone upside?',
 'Price synthetic three-month European options using Black–Scholes. Compare an unhedged underlying, a 90-strike protective put and a 90/110 collar. Include premium cash opportunity cost and per-leg fees; compare 15%, 25%, 40% assumed volatility.',
 'State the loss floor, upside cap and funding cost explicitly before calling a hedge attractive. These payoffs do not establish that insurance is cheap.',
 'Real implied skew, bid/ask costs, dividends, American exercise and basis risk can materially change the trade.',
 'Source a dated option chain and contract specifications; write a cash-funded prospective hedge thesis before any paper fill.',
 'Derive put–call parity and explain why P&L divided by underlying notional is not return on option premium.',
 ['blackscholes','cboehedges'],[['project/stress','Loss scenarios']],'Synthetic option mechanics'),
 project('decision-log','Prospective thesis and probability register','Data & engineering','decisionlog.py',
 'How can future investment judgements become auditable evidence?',
 'Validate append-only forecasts and resolutions with timestamped information cutoffs, explicit outcome rules and a SHA-256 chain. Compute binary Brier scores only for resolved registered forecasts. The empty initial register is separate from a synthetic proper-scoring demonstration.',
 'Record probabilities, alternatives and invalidation rules before events. Preserve mistakes and unresolved outcomes; connect any later trade to the original thesis.',
 'A rewritten hash chain, selective resolution or vague event definition destroys evidential value. A Git timestamp alone does not verify source availability.',
 'Enter the first owner-approved forecast with scripts/record_decision.py and publish its commit before the outcome; retain an external timestamp anchor.',
 'Why does a proper scoring rule encourage honest probabilities, and why is a low score meaningless without a base-rate benchmark?',
 ['proper_scores'],[['journal','Decision journal'],['lab-setup','Run locally']],'Prospective infrastructure; zero forecasts')
]
